---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
  remote.services: 
    CommTableService:
       destination:
            type: "odata-v2"
    
      
