---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false
---
spring:
  config.activate.on-profile: cloud
cds:
  remote.services:
    HrService:
      destination:
        name: "CommTableService"
        type: "odata-v2"