---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false

---
spring:
  config.activate.on-profile: cloud
cds:
  remote.services:
    API_BUSINESS_PARTNER:
      destination:
        type: "odata-v2"
        properties:
            url: "https://api.cf.eu10.hana.ondemand.com"
        headers:
            APIKey: "" # Place API Key from SAP API Business Hub here or use environment variable CDS_REMOTE_SERVICES_API_BUSINESS_PARTNER_DESTINATION_HEADERS_APIKEY
